name: Build Nuitka so
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Nuitka
        run: |
          python -m pip install --upgrade pip
          pip install nuitka

      - name: Build with Nuitka
        run: |
          # 编译为 Python 模块 (so)
          python -m nuitka --module app --include-package=app
          ls -lh


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-so
          path: app*.so
